blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    #path('', views.post_list, name="post_list"),
    path('', views.PostListView.as_view(), name="post_list"),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, name="post_detail"),
    path('<int:post_id>/share/', views.post_share, name="post_share"),
    path('register', views.register, name="register"),
    path('login', views.loginPage, name="login"),
    path('logout', views.logoutUser, name="logout"),
    path('writeblog', views.writeblog, name="writeblog"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'),)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now())
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    objects = models.Manager()  # The  Default Manager
    published = PublishedManager()  # Our Custom Manager

    def get_absolute_url(self):
        #pylint: disable=E1101
        return reverse("blog:post_detail", args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import Post


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class BlogForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'slug', 'author', 'body', 'status']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CreateUserForm, BlogForm
from django.core.mail import send_mail
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

# Create your views here.


def post_list(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published',
                             publish__year=year, publish__month=month, publish__day=day)
    return render(request, 'blog/post/detail.html', {'post': post})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_share(request, post_id):
    # Retrieve Post By Id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    # Form was submitted
    if request.method == "POST":
        form = EmailPostForm(request.POST)
        # Form fields passed the validation
        if form.is_valid():
            cd = form.cleaned_data
            # send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url} \n \n" \
                f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message,
                      'prasannasomoshi@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def register(request):
    form = CreateUserForm()

    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(
                request, 'Account succesfully created for ' + user)
            return redirect('blog:login')

    context = {'form': form}
    return render(request, 'register.html', context)


def loginPage(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('/blog')
        else:
            messages.info(request, "Username or Password is incorrect!")

    context = {}
    return render(request, 'login.html')


def logoutUser(request):
    logout(request)
    return redirect('blog:login')


def writeblog(request):
    form = BlogForm()
    if request.method == "POST":

        form = BlogForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("blog:post_list")

    return render(request, "blogform.html", {'form': form})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">

</head>

<body>
    <!-- NavBar-->

    {% include 'navbar.html' %}

    <!-- End NavBar-->

    <div id="content">

        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        {% if user.is_authenticated %}
        <h2>Welcome {{user}}!</h2><br>
        {% endif %}
        <p>Happy Blogging!</p>
    </div>



</body>

</html>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}

{% block  title %} {{ post.title }}
{% endblock %}

{% block content %}


<h1>{{ post.title }}</h1>
<p class="date"> Published {{post.publish}} by {{post.author}}</p>

{{ post.body | linebreaks }}

<p>
    <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
</p>


{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}
My Blog
{% endblock title %}

{% block content %}
<h1>My Blog</h1>

{% for post in posts %}

<h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
<p class="date">Published {{post.publish}} by {{ post.author }}</p>

{{ post.body | truncatewords:30 | linebreaks }}


{% endfor %}

{% include 'pagination.html' with page=page_obj %}

{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %} Share a post
{% endblock %}

{% block content %}

{% if sent %}
<h1>E-mail sent successfully</h1>
<p> "{{post.title}}" was successfully sent to {{ form.cleaned_data.to }}</p>
{% else %}
<h1>Share "{{post.title}}" by e-mail</h1>


<form action="" method="POST">

    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Send E-mail">


</form>


{% endif %}

{% endblock %}

blog/templates/blogform.html
{% extends "blog/base.html" %}

{% block title %} Write Blog
{% endblock %}

{% block content %}

<h1>Write your blog</h1>

<div class="blogform" id="bf">
    <form action="" method="POST">


        {% csrf_token %}
        <!--
           {% for field in form  %}
        {{field.label}}
        {{field}}
        {% endfor %}
        -->



        <p>{{form.title.label}}</p>
        {{form.title}}<br><br>

        <p>{{form.slug.label}}</p>
        {{form.slug}}<br><br>

        {{form.author.label}}
        {{form.author}}<br><br>


        <p>{{form.body.label}}</p>
        {{form.body}}
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>

        {{form.status.label}}
        {{form.status}}

        <p>{{form.STATUS_CHOICES.label}}</p>
        {{form.STATUS_CHOICES}}

        <input type="submit" value="Post">


    </form>
</div>


{% endblock %}

blog/templates/login.html
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
        integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
            background: #1A2980;
            /* fallback for old browsers */
            background: -webkit-linear-gradient(to right, #26D0CE, #1A2980);
            /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to right, #26D0CE, #1A2980);
            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        }

        .user_card {
            width: 350px;
            margin-top: 40px;
            margin-bottom: auto;
            background: #74cfbf;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            color: #fff;

        }

        .login_btn {
            width: 100%;
            background: #33ccff !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        #messages {
            background-color: grey;
            color: #fff;
            padding: 10px;
            margin-top: 10px;
        }
    </style>

</head>

<body>

    {% include 'navbar.html' %}

    <center>
        <h1 style="color: white; margin-top: 10px;">Welcome to Sam's Blog</h1>
    </center>

    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="user_card">
                <div class="d-flex justify-content-center">


                    <h3 id="form-title">LOGIN</h3>
                </div>
                <div class="d-flex justify-content-center form_container">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input type="text" name="username" placeholder="Username..." class="form-control">
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            <input type="password" name="password" placeholder="Password..." class="form-control">
                        </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                            <input class="btn login_btn" type="submit" value="Login">
                        </div>
                    </form>

                </div>


                {% for message in messages  %}

                <p id="messages">{{message}}</p>

                {% endfor %}

                <div class="mt-4">
                    <div class="d-flex justify-content-center links">
                        Don't have an account? <a href="{% url 'blog:register' %}" class="ml-2">Sign Up</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</body>

</html>

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    {% if user.is_authenticated %}
    <a class="navbar-brand" href="/blog">Sam's blog</a>
    {% else %}
    <a class="navbar-brand" href="/blog/register">Sam's blog</a>
    {% endif %}

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>




    {% if user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/blog">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/blog/writeblog">Write Blog</a>
            </li>
            <!-- Log out button was here -->
        </ul>
        {% else %}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/blog/register">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/blog/login">Log in</a>
                </li>

            </ul>
            {% endif %}


            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                {% if user.is_authenticated %}
                <a style="color: white;" class="nav-link" href="/blog/logout">Log Out</a>
                {% endif %}
            </form>
        </div>
</nav>

<br>

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

blog/templates/register.html
<!DOCTYPE html>
<html>

<head>
    <title>Register</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
        integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
            background: #1A2980;
            /* fallback for old browsers */
            background: -webkit-linear-gradient(to right, #26D0CE, #1A2980);
            /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to right, #26D0CE, #1A2980);
            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

        }

        .user_card {
            width: 350px;
            margin-top: 40px;
            margin-bottom: auto;
            background: #74cfbf;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            color: #fff;
        }

        .login_btn {
            width: 100%;
            background: #33ccff !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }
    </style>

</head>

<body>

    {% include 'navbar.html' %}
    <center>
        <h1 style="color: white; margin-top: 10px;">Welcome to Sam's Blog</h1>
    </center>

    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="user_card">
                <div class="d-flex justify-content-center">
                    <h3 id="form-title">REGISTER ACCOUNT</h3>
                </div>
                <div class="d-flex justify-content-center form_container">

                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            {{form.username}}
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                            </div>
                            {{form.email}}
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            {{form.password1}}
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            {{form.password2}}
                        </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                            <input class="btn login_btn" type="submit" value="Register Account">
                        </div>
                    </form>
                </div>

                {{form.errors}}

                <div class="mt-4">
                    <div class="d-flex justify-content-center links">
                        Already have an account? <a href="{% url 'blog:login' %}" class="ml-2">Login</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <script>
        /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

        //Query All input fields
        var form_fields = document.getElementsByTagName('input')
        form_fields[2].placeholder = 'Username..';
        form_fields[3].placeholder = 'Email..';
        form_fields[4].placeholder = 'Enter password...';
        form_fields[5].placeholder = 'Re-enter Password...';


        for (var field in form_fields) {
            form_fields[field].className += ' form-control'
        }
    </script>
</body>

</html>